versions:
- "2.6":
    code_name: "HeartBreaker"
    releases:
    - "0": "TBD"
- "2.5":
    code_name: "Kashmir"
    releases:
    - "5": "14-06-2018"
    - "4": "31-05-2018"
    - "3": "17-05-2018"
    - "2": "26-04-2018"
    - "1": "19-04-2018"
    - "0": "23-03-2018"
- "2.4":
    code_name: "Dancing Days"
    releases:
    - "5": "06-21-2018"
    - "4": "04-04-2018"
    - "3": "01-31.2018"
    - "2": "11-29-2017"
    - "1": "10-25-2017"
    - "0": "09-19-2017"
- "2.3":
    code_name: "Ramble On"
    releases:
    - "2": "08-04-2017"
    - "1": "06-01-2017"
    - "0": "04-12-2017"
- "2.2":
    code_name: "The Battle of Evermore"
    releases:
    - "3": "05-09-2017"
    - "2": "03-27-2017"
    - "1": "01-16-2017"
    - "0": "11-01-2016"
- "2.1":
    code_name: "The Song Remains the Same"
    releases:
    - "6": "06-01-2017"
    - "5": "03-27-2017"
    - "4": "01-16-2017"
    - "3": "11-04-2016"
    - "2": "09-29-2016"
    - "1": "07-28-2016"
    - "0": "05-25-2016"
- "2.0":
    code_name: "Over the Hills and Far Away"
    releases:
    - '2': "04-19-2016"
    - '1': "02-24-2016"
    - '0': "01-12-2016"
- "1.9":
    code_name: "Dancing In the Streets"
    releases:
    - '6': "04-15-2016"
    - '5': "03-21-2016"
    - '4': "10-09-2015"
    - '3': "09-03-2015"
    - '2': "06-24-2015"
    - '1': "04-27-2015"
    - '0': "03-25-2015"
- "1.8":
    code_name: "You Really Got Me"
    releases:
    - '4': "02-19-2015"
    - '3': "02-17-2015"
    - '2': "12-04-2014"
    - '1': "11-26-2014"
    - '0': "11-25-2014"
- "1.7":
    code_name: "Summer Nights"
    releases:
    - '2': "09-24-2014"
    - '1': "08-14-2014"
    - '0': "08-06-2014"
- "1.6":
    code_name: "The Cradle Will Rock"
    releases:
    - '10': "07-25-2014"
    - '9': "07-24-2014"
    - '8': "07-22-2014"
    - '7': "07-21-2014"
    - '6': "07-01-2014"
    - '5': "06-25-2014"
    - '4': "06-25-2014"
    - '3': "06-09-2014"
    - '2': "05-23-2014"
    - '1': "05-07-2014"
    - '0': "05-05-2014"
- "1.5":
    code_name: "Love Walks In"
    releases:
    - '5': "04-18-2014"
    - '4': "04-01-2014"
    - '3': "03-13-2014"
    - '2': "03-11-2014"
    - '1': "03-10-2014"
    - '0': "02-28-2014"
- "1.4":
    code_name: "Could This Be Magic?"
    releases:
    - '5': "02-12-2014"
    - '4': "01-06-2014"
    - '3': "12-20-2013"
    - '2': "12-18-2013"
    - '1': "11-27-2013"
    - '0': "11-21-2013"
- "1.3":
    code_name: "Top of the World"
    releases:
    - '4': "10-29-2013"
    - '3': "10-09-2013"
    - '2': "09-19-2013"
    - '1': "09-16-2013"
    - '0': "09-13-2013"
- "1.2":
    code_name: "Right Now"
    releases:
    - '3': "08-21-2013"
    - '2': "07-05-2013"
    - '1': "07-04-2013"
    - '0': "06-10-2013"
- "1.1":
    code_name: "Mean Street"
    releases:
    - '0': "04-02-2013"
- "1.0":
    code_name: "Eruption"
    releases:
    - '0': "02-01-2013"
- "0.9":
    code_name: "Dreams"
    releases:
    - '0': "11-30-2012"
- "0.8":
    code_name: "Cathedral"
    releases:
    - '0': "10-19-2012"
- "0.7":
    code_name: "Panama"
    releases:
    - '0': "09-06-2012"
- "0.6":
    code_name: "Cabo"
    releases:
    - '0': "08-06-2012"
- "0.5":
    code_name: "Amsterdam"
    releases:
    - '0': "07-04-2012"
- "0.4":
    code_name: "Unchained"
    releases:
    - '0': "05-23-2012"
- "0.3":
    code_name: "Baluchitherium"
    releases:
    - '0': "04-23-2012"
- "0.2":
    code_name: "Untitled"
    releases:
    - '0': "?"
- "0.1":
    code_name: "Untitled"
    releases:
    - '0': "?"
- "0.0":
    code_name: "Untitled"
    releases:
    - '2': "?"
    - '1': "?"
